### ISSUE TITLE
Tag a Release

### ISSUE THREAD

**Issue by haneefmubarak** [timrc-git/mdbm#9]
Hey @timrc-git,

Could you tag a release at the latest point that seems reasonable to you? I'd like to use this as a dep in a project, but it'd be nice to refer to a tagged release as opposed to HEAD.

Thanks!

**Comment by timrc-git** [comment]
https://github.com/timrc-git/mdbm/releases/tag/V4.12.4

**Comment by haneefmubarak** [comment]
Awesome. Thanks @timrc-git!
